"""VynCo Python SDK — Python client for the VynCo Swiss Corporate Intelligence API."""

from __future__ import annotations

from vynco._client import AsyncClient, Client
from vynco._constants import __version__
from vynco._errors import (
    AuthenticationError,
    ConfigError,
    ConflictError,
    DeserializationError,
    ForbiddenError,
    InsufficientCreditsError,
    NotFoundError,
    RateLimitError,
    ServerError,
    ServiceUnavailableError,
    ValidationError,
    VyncoError,
)
from vynco._response import Response, ResponseMeta
from vynco.types import (
    AddCompaniesResponse,
    AiSearchResponse,
    AnomalyResponse,
    ApiKey,
    ApiKeyCreated,
    AuditCandidate,
    AuditorHistoryResponse,
    AuditorMarketShare,
    AuditorTenure,
    BillingSummary,
    BoardMember,
    CantonDistribution,
    ChangeStatistics,
    ClusterResponse,
    CohortResponse,
    Company,
    CompanyChange,
    CompanyCount,
    CompanyReport,
    CompanyStatistics,
    CompareResponse,
    CreateWebhookResponse,
    CreditBalance,
    CreditHistory,
    CreditLedgerEntry,
    CreditUsage,
    DashboardResponse,
    Dossier,
    DossierResponse,
    DossierSummary,
    EventListResponse,
    ExportDownload,
    ExportJob,
    Fingerprint,
    GraphLink,
    GraphNode,
    GraphResponse,
    HealthResponse,
    HierarchyResponse,
    Invitation,
    NearbyCompany,
    NetworkAnalysisResponse,
    NewsItem,
    PaginatedResponse,
    Relationship,
    RfmSegmentsResponse,
    RiskFactor,
    RiskScoreResponse,
    ScreeningHit,
    ScreeningResponse,
    SessionUrl,
    Team,
    TeamMember,
    TestDeliveryResponse,
    Watchlist,
    WatchlistCompaniesResponse,
    WatchlistSummary,
    WebhookDelivery,
    WebhookSubscription,
)

__all__ = [
    # Version
    "__version__",
    # Clients
    "AsyncClient",
    "Client",
    # Errors
    "VyncoError",
    "AuthenticationError",
    "InsufficientCreditsError",
    "ForbiddenError",
    "NotFoundError",
    "ValidationError",
    "ConflictError",
    "RateLimitError",
    "ServerError",
    "ServiceUnavailableError",
    "ConfigError",
    "DeserializationError",
    # Response
    "Response",
    "ResponseMeta",
    # Types
    "PaginatedResponse",
    "HealthResponse",
    "Company",
    "CompanyCount",
    "CompanyStatistics",
    "EventListResponse",
    "CompareResponse",
    "NewsItem",
    "CompanyReport",
    "Relationship",
    "HierarchyResponse",
    "Fingerprint",
    "NearbyCompany",
    "AuditorHistoryResponse",
    "AuditorTenure",
    "AuditorMarketShare",
    "DashboardResponse",
    "ScreeningResponse",
    "ScreeningHit",
    "Watchlist",
    "WatchlistSummary",
    "WatchlistCompaniesResponse",
    "AddCompaniesResponse",
    "WebhookSubscription",
    "CreateWebhookResponse",
    "TestDeliveryResponse",
    "WebhookDelivery",
    "ExportJob",
    "ExportDownload",
    "DossierResponse",
    "AiSearchResponse",
    "RiskScoreResponse",
    "RiskFactor",
    "ApiKey",
    "ApiKeyCreated",
    "CreditBalance",
    "CreditUsage",
    "CreditHistory",
    "CreditLedgerEntry",
    "SessionUrl",
    "Team",
    "TeamMember",
    "Invitation",
    "BillingSummary",
    "CompanyChange",
    "ChangeStatistics",
    "BoardMember",
    "CantonDistribution",
    "ClusterResponse",
    "AnomalyResponse",
    "RfmSegmentsResponse",
    "CohortResponse",
    "AuditCandidate",
    "Dossier",
    "DossierSummary",
    "GraphResponse",
    "GraphNode",
    "GraphLink",
    "NetworkAnalysisResponse",
]
